---
- hosts: rocky
  user: sysadmin
  become: yes

  tasks:

  - name: Apache est치 instalado
    ansible.builtin.dnf:
      name: httpd
      state: present

  - name: Copiar configuraci칩n del proxy
    ansible.builtin.copy:
      src: ./files/proxy.conf
      dest: /etc/httpd/conf.d
      owner: root
      group: root
      mode: '0644'
    notify: Reiniciar apache

  - name: Apache est치 iniciado y habilitado
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: true

  - name: Habilito el servicio http en firewalld
    ansible.posix.firewalld:
      service: http
      state: enabled
      permanent: true
      immediate: true

  - name: Instalo paquetes para manejar selinux
    ansible.builtin.dnf:
      name: python3-libsemanage
      state: present
  
  - name: Configuro selinux para permitir conexi칩n con el tomcat
    ansible.posix.seboolean:
      name: "{{ item }}"
      state: true
      persistent: true
    loop:
    - httpd_can_network_relay
    - httpd_can_network_connect
    notify: Reiniciar apache

  handlers:

  - name: Reiniciar apache
    ansible.builtin.service:
      name: httpd
      state: restarted
     
