---
- hosts: linux
  user: sysadmin
  become: true

  tasks:

  - name: Update packages in Rocky Server
    ansible.builtin.yum:
      name: "*"
      state: latest
    when: ansible_os_family == "RedHat"
    notify: Reboot server

  - name: Update packages in Ubuntu Server
    ansible.builtin.apt:
      name: "*"
      state: latest
      update_cache: yes
    when: ansible_os_family == "Debian"
    notify: Reboot server

  handlers:

  - name: Reboot server
    ansible.builtin.reboot:
      reboot_timeout: 300
    
